import { IEmployee, StatusEnum } from "./interfaces";

export const mok_data: IEmployee[] = [
    {
        id: "1",
        name: "Darlene Robertson",
        email: "trungkienspktnd@gamail.com",
        status: StatusEnum.FREE,
        role: "Reporter",
    },
    {
        id: "2",
        name: "John Smith",
        email: "john@example.com",
        status: StatusEnum.BUSY,
        role: "Developer",
    },
    {
        id: "3",
        name: "Alice Johnson",
        email: "alice@example.com",
        status: StatusEnum.WORKIN,
        role: "Manager",
    },
    {
        id: "4",
        name: "Michael Brown",
        email: "michael@example.com",
        status: StatusEnum.ON_VACATION,
        role: "Designer",
    },
    {
        id: "5",
        name: "Emily Davis",
        email: "emily@example.com",
        status: StatusEnum.FREE,
        role: "Engineer",
    },
    {
        id: "6",
        name: "Daniel Garcia",
        email: "daniel@example.com",
        status: StatusEnum.BUSY,
        role: "Analyst",
    },
    {
        id: "7",
        name: "Sophia Martinez",
        email: "sophia@example.com",
        status: StatusEnum.WORKIN,
        role: "Consultant",
    },
    {
        id: "8",
        name: "Matthew Wilson",
        email: "matthew@example.com",
        status: StatusEnum.ON_VACATION,
        role: "Administrator",
    },
    {
        id: "9",
        name: "Olivia Taylor",
        email: "olivia@example.com",
        status: StatusEnum.FREE,
        role: "Coordinator",
    },
    {
        id: "10",
        name: "David Rodriguez",
        email: "david@example.com",
        status: StatusEnum.BUSY,
        role: "Supervisor",
    },
    {
        id: "11",
        name: "Sophia Brown",
        email: "sophia@example.com",
        status: StatusEnum.WORKIN,
        role: "Specialist",
    },
    {
        id: "12",
        name: "James Wilson",
        email: "james@example.com",
        status: StatusEnum.ON_VACATION,
        role: "Technician",
    },
    {
        id: "13",
        name: "Emma Johnson",
        email: "emma@example.com",
        status: StatusEnum.FREE,
        role: "Developer",
    },
    {
        id: "14",
        name: "Ethan Martinez",
        email: "ethan@example.com",
        status: StatusEnum.BUSY,
        role: "Designer",
    },
    {
        id: "15",
        name: "Isabella Taylor",
        email: "isabella@example.com",
        status: StatusEnum.WORKIN,
        role: "Engineer",
    },
    {
        id: "16",
        name: "Liam Brown",
        email: "liam@example.com",
        status: StatusEnum.ON_VACATION,
        role: "Analyst",
    },
    {
        id: "17",
        name: "Ava Martinez",
        email: "ava@example.com",
        status: StatusEnum.FREE,
        role: "Consultant",
    },
    {
        id: "18",
        name: "Mason Wilson",
        email: "mason@example.com",
        status: StatusEnum.BUSY,
        role: "Administrator",
    },
    {
        id: "19",
        name: "Charlotte Johnson",
        email: "charlotte@example.com",
        status: StatusEnum.WORKIN,
        role: "Coordinator",
    },
    {
        id: "20",
        name: "Logan Rodriguez",
        email: "logan@example.com",
        status: StatusEnum.ON_VACATION,
        role: "Supervisor",
    },
];
